project:
  type: book  
book:
  title: "Introductie R en Shiny"
  author: "David Macro"
  date: "2024 03 03"
  chapters: 
    - index.qmd
    - intro.qmd 
    - part: mod1_basis.qmd
      chapters:  
        - mod1_variables.qmd  
        - mod1_datatypes.qmd  
        - mod1_flow.qmd
    - part: mod2_datatableintro.qmd
      chapters: 
        - mod2_datatableijby.qmd
    - part: mod3_plotlyintro.qmd 
      chapters:  
        - mod3_plotlybarchart.qmd  
    - part: mod4_advancedintro.qmd
      chapters:
        - mod4_fp.qmd
    - part: mod5_basicshinyintro.qmd
      chapters:
        - mod5_basicshinycomponents.qmd
    - references.qmd 
bibliography: references.bib  
sidebar: 
    search: true
format:   
  html:
    page-layout: full
    toc-depth: 4
    grid:  
      body-width: 900px
      sidebar-width: 350px
      margin-width:	150px
      content-mode: full
    theme:  yeti 
    code-block-bg: true
    code-block-border-left: true
    css: stylesheet.css 
editor: source

