project:
  type: book  
book:
  title: "Introductie R en Shiny"
  author: "David Macro"
  date: "2024 03 03"
  chapters: 
    - index.qmd
    - part: intro.qmd 
    - part: mod1_basis.qmd
      chapters: 
        - mod1_variables.qmd  
        - mod1_datatypes.qmd  
        - mod1_flow.qmd
    - part: mod2_advanced.qmd
      chapters:
        - mode2_fp.qmd
    - part: "Charts met Plotly" 
    - references.qmd 
bibliography: references.bib 
sidebar: 
    search: true
format:  
  html:
    page-layout: full
    toc-depth: 4
    grid: 
      content-mode: full
    theme:  yeti 
    code-block-bg: true
    code-block-border-left: true
    css: stylesheet.css 
editor: source

